### ISSUE TITLE
Špatné umístění ikonek pro kompletaci větve

### ISSUE THREAD

**Issue by honza-stepanek** [honzaflash/dvzka#1]
Na listu "crossroads" se větví DVZ podle toho, jaký styl argumentační chyby chce student prostudovat. Aby studenti měli nějakou vizuální stopu, že už tu či onu větev prošli, objeví se po její kompletaci zaškrtávátko. Je to řešeno následovně:
`[[Snaha zabránit protistraně v&nbsp;argumentaci.|freedom ]] |free)[  &checkmark;]`
Momentálně se ten checkmark posune na následující řádek pod tlačítko, takže není úplně jasné, k čemu patří.
Jako bonus by možná bylo dobré přijít s nějakou viditelnější variantou – tohle byl můj pokus na poslední chvíli, když jsme potřebovali prototyp rychle někam odeslat a pak už jsem se k tomu neměl čas vracet.
![2021-02-26 12_02_58-Kritické myšlení](https://user-images.githubusercontent.com/32508313/109297736-c2fd2500-7832-11eb-8fe9-19b63f1f6dab.png)

**Comment by honzaflash** [comment]
Obalil jsem to celé do pojmenovaného hooku, přes něj to vše zvlášť nastyloval a taky jsem vyměnil ten znak za svg checkmark z wikimedia commons :)
Je to [commitnuté](https://github.com/honzaflash/dvzka/commit/afaa745f71894e8fb21653d295bec9a3626c20e8).
![image](https://user-images.githubusercontent.com/74110240/109420072-de9e3200-79d0-11eb-9ef3-d185f6a7b119.png)
![image](https://user-images.githubusercontent.com/74110240/109420056-c8907180-79d0-11eb-870b-0d2d134f5267.png)
To posunutí byl vedlejší produkt toho že jsem se rozhodl tlačítka zarovnat na střed pomocí `display: block; magrin: auto` takže teď zabírají celou šířku a to vytlačí cokoliv z toho řádku jako ty checkmarky včetně `<br>` tagů, takže to pak celé budu muset ještě projít a asi některé ty newlines odescapovat.
