### ISSUE TITLE
Velikost obrazů pro spouštění modalů

### ISSUE THREAD

**Issue by honza-stepanek** [honzaflash/dvzka#11]
Obrazy v příběhu, které spouštějí modaly, jsou momentálně na Full HD displejích roztáhnuty přes celý příběh, což je ale víc, než je jejich rozlišení, takže se rozpixelují. Nebylo by lepší jim nechat místo width max-width na 100 %?

**Comment by honzaflash** [comment]
Jsem si toho vědom. Moc pěné to není... oni tedy ty obrázky jako takové nesjou žádná sláva, ale roztažení jim určitě nepřidává.

Zkusil jsem jim dát `max-width: 100%`, jak jsi, říkal a vycentrovat. Nevypadá to špatně, ale jiné obrázky jsou pak větší a působí to nekonzistentně - jako kdybychom chtěli aby ten obrázek byl `width: 100%` ale u některých se nám to nepodařilo. (což teda tak vpodstatě je 😄)
<img src="https://user-images.githubusercontent.com/74110240/112679088-0f587680-8e6c-11eb-8110-4bbf6bae0323.png" width=350> <img src="https://user-images.githubusercontent.com/74110240/112679265-3f077e80-8e6c-11eb-9cbc-f1dabe24df0a.png" width=350>

Třetí možnost je dát jim ještě `width: 570px` a pak jsou všechny stejně široké, vycentrované a vypadá to docela ok.

<img src="https://user-images.githubusercontent.com/74110240/112679185-2a2aeb00-8e6c-11eb-9fb0-5532196ffdeb.png" width=350>

Předtím se mi líbilo, jak to bylo takové jednoduché a rovnoměrné, ale zase bych řekl, že ty obrázky pak zabíraly moc místa. Možná bude možnost č. 3 teda nejlepší.
