### ISSUE TITLE
Problematický PDF reader v mh06

### ISSUE THREAD

**Issue by honza-stepanek** [honzaflash/dvzka#13]
V mh06 je v modalu PDF, které se otevře přímo v něm. Když si to pustím doma na live serveru z Visual Studia Code, všechno funguje ok, ale když to pustím na webu z https://digikult.phil.muni.cz/wp-content/DVZ/kriticke-mysleni/kriticke_mysleni.html, tak mi nejde skoro na nic kliknout. A jelikož ten učitel měl menší monitor, nešlo mu kliknout na nic. Když jsem na to koukal blíže, zjistil jsem, že tu stránku překrývá nejspíš právě ten prohlížeč PDF, jelikož jeho plocha dokonale ořezává oblast odkazu v citaci na horní straně stránky, na kterou můžu, resp. nemůžu kliknout. Napadá tě, co s tím?
![2021-03-29 10_53_35-Messenger](https://user-images.githubusercontent.com/32508313/112852524-4fa63780-90ac-11eb-8336-6f67e4b9fd4b.png)

**Comment by honzaflash** [comment]
To je fakt bizardní. Ve Firefoxu mi to problém nedělá, ale v chromu, přesně jak říkáš, tam ten pdf viwer reaguje na myš a ignoruje `pointer-events: none` - teda spíš asi ta aplikace uvnitř to nedědí, i když ten `div.modalDialog` je má.
Vyřešil jsem to "krásně" nastavením `top: 200vh`, takže pokud ten modal není targetnutý, ten pdf viewer je odpálený o dvě obrazovky níž 😂
Taky teda nebyl ani zarovnaný na střed, tak jsem ho ještě k tomu trochu nastyloval.

<img width="400px" src="https://user-images.githubusercontent.com/74110240/112873690-40ca7f80-90c2-11eb-98c3-3e1e99e9ae60.png"/>
