### ISSUE TITLE
Stylování tlačítek pro (click:) makro

### ISSUE THREAD

**Issue by honza-stepanek** [honzaflash/dvzka#2]
Tohle předpokládám není chyba, ale něco, co zatím není hotové, tak jen pro jistotu. Na místech, kde používám jako odkazy klikací hooky, jako např. na stranách "ad-hominem-syflak", "mh02" nebo "mandelinka2", se objevují stará tlačítka. Mám to nastavené jako hooky, které jsou následně udělané pomocí makra (click:) jako klikací. V CSS je mám stylované jako:
```
tw-hook[name^='ch'] {
    box-shadow: 3px 3px 10px darkgray;
    background-color: white;
    border: #4BC8FF solid;
    border-radius: 35px;
    display: inline-block;
    cursor: pointer;
    color: black;
    font-weight: bold;
    padding: 15px 20px;
    text-decoration: none;
    margin: 1%;
    text-align: center;
    width: 50%;
}
tw-hook[name^='ch']:hover {
    background-color: #4BC8FF;
    color: cyan;
    color: white;
}
tw-hook[name^='ch']:active {
    position: relative;
    top: 2px;
}
```
Takže tady vlastně jen stačí změnit CSS.
![2021-02-26 13_10_06-Kritické myšlení](https://user-images.githubusercontent.com/32508313/109298554-10c65d00-7834-11eb-916d-1833a0428b6c.png)

**Comment by honzaflash** [comment]
Jelikož to nepřepíná pasáž, přijde mi, že není špatné to udělat jednotně s ostatními makry typu "reveal text," které podle všeho všechna vytvářejí `<tw-enchantment class="... enchantment-link" ...>`
Napadlo mě něco takového:
![image](https://user-images.githubusercontent.com/74110240/109425196-760e7f80-79e7-11eb-804a-49de301f0ca0.png)

Protože mají `display: inline`, ignorují vertikální margin. U těch které máš označené "ch#" bych ale mohl display změnit na inline-block a dát jim trochu víc prosotru (tak to momentálně je):
![image](https://user-images.githubusercontent.com/74110240/109425216-8f173080-79e7-11eb-8e92-cd4fde86c6ca.png)
Ostatní ale zůstávají s normální výškou:
![image](https://user-images.githubusercontent.com/74110240/109426539-7eb68400-79ee-11eb-947f-623d23bbcb2b.png)
![image](https://user-images.githubusercontent.com/74110240/109426671-1fa53f00-79ef-11eb-899d-f249d1f29533.png)

**Comment by honza-stepanek** [comment]
Jo, to vypadá dobře. Tlačítko v těchhle kontextech není nutný.
