### ISSUE TITLE
Písmo reakcí v případu Milady Horákové

### ISSUE THREAD

**Issue by honza-stepanek** [honzaflash/dvzka#3]
V procesu s Miladou horákovou mám na slidech "mh05a", "mh05b" a "mh05c" umístěný vysvětlijící text, který komentuje volbu studenta. Text komentáře je ale špatně rozeznatelný od zbytku textu na straně a je možné, že ho studenti v rychlosti minou nebo přehlédnou. Bylo by možné ty části v komentářích nějak lépe/více zviditelnit? Momentálně to mám nastylované jako `<p class="commie">`.
![2021-02-26 12_07_35-](https://user-images.githubusercontent.com/32508313/109299365-44ee4d80-7835-11eb-9d16-9f3f51a2f22d.png)

P.S.: Omlouvám se, že u Milady Horákové mám barvu textu spouštějícího modaly upravenou inline v tagu `<a>`. Zhrozil jsem se, když jsem si toho teď všiml.

**Comment by honzaflash** [comment]
Buď to nebylo dost výrazné nebo to byl barevný chaos tak jsem to nakonec vyřešil bublinou jako je `.imbox`.
