### ISSUE TITLE
Pozice žárovky na pozadí

### ISSUE THREAD

**Issue by honza-stepanek** [honzaflash/dvzka#5]
Ahoj! Na poradě jsem ukazoval pracovní verzi Kritického myšlení a moc se líbila. Všimli jsme si ale, že žárovka se nám zobrazuje každému trochu jinak (viz přiložené obrázky).
Bylo by možné to udělat tak, aby ta žárovka víc vykukovala i na menších rozlišeních? Takže by její levá část byla schovaná pod plochou příběhu, ale její svítící část přesahovala?
![hs_zarovka](https://user-images.githubusercontent.com/32508313/109504215-95ff7b00-7a9b-11eb-8ea4-63f3d3562dd0.png)
![mm_zarovka](https://user-images.githubusercontent.com/32508313/109504220-9730a800-7a9b-11eb-80fc-01c6268d7de9.png)

**Comment by honzaflash** [comment]
Hmmm, pozadí je totiž nastavené jako `cover` takže je fixní nehledě na rozlišení nebo **přiblížení**. Změnit bych to asi mohl, už nevím jaká byla moje motivace k tomu nastavení 🙄 whoops.
Teď se mi to ale hodí, protože jsem tu žárovku přidal i do obrázku soudní síně a bramborového pole, takže když se to pozadí změní ta žárovka je tam jako jeden stálý prvek. Pokud bych odebral `cover` zobrazení jen u toho obecného pozadí tak při změně se žárovka bude posouvat, pokud bych to odebral u všech tak při odzoomování nebo při větším rozlišení ten obrázek nebude přes celou obrazovku (dá se dlaždicově opakovat nebo tam dát nějakou barvu)
![image](https://user-images.githubusercontent.com/74110240/109548667-391cb880-7acd-11eb-80a9-735a0d757fe3.png)

**Comment by honzaflash** [comment]
Opraveno v commitu [94a77b1451b14d12be665e72723b4ae6ffa18595](https://github.com/honzaflash/dvzka/commit/94a77b1451b14d12be665e72723b4ae6ffa18595)
