### ISSUE TITLE
Rzohodování – autoři

### ISSUE THREAD

**Issue by honza-stepanek** [honzaflash/dvzka#8]
- U autorů jsou všichni z kisku na jednom řádku.
- Ještě prosím nahradit odkaz u Michala Černého za https://is.muni.cz/go/mcerny.

![image](https://user-images.githubusercontent.com/32508313/112167377-b03afd80-8bf0-11eb-91c9-26f504f496ec.png)

**Comment by honzaflash** [comment]
upraveno - [commit](https://github.com/honzaflash/dvzka/commit/10cac773452bd0e73d9292f9803ab5b6ce03280c)
