### ISSUE TITLE
Text pod logolinkem

### ISSUE THREAD

**Issue by honza-stepanek** [honzaflash/dvzka#9]
Tohle se týká Rozhodování i Kritického myšlení. Písmo s nápisem: "Vytvořeno v rámci projektu…" Je celkem velké. U Mandelinky je to `font-size: small;`, zatímco v těchhle je to `font-size: smaller;` (KM) a `font-size: 75%;` (Rozh.). Nebál bych se to změnšit na úroveň mandelinky a v případě MK posunout níž.
![image](https://user-images.githubusercontent.com/32508313/112168539-aebe0500-8bf1-11eb-8ad9-d1bfae7918b3.png)
![image](https://user-images.githubusercontent.com/32508313/112168621-be3d4e00-8bf1-11eb-8e22-d1e1565a95b0.png)
![image](https://user-images.githubusercontent.com/32508313/112168644-c39a9880-8bf1-11eb-890d-74410fe5ccbd.png)

**Comment by honzaflash** [comment]
Nahraný [commit](https://github.com/honzaflash/dvzka/commit/f3ff06fd0af2bd42191048c12423258afe925826) s opravou. Zmenšil jsem to všechno na `small`  a v Rozhodování (to jsi asi myslel místo "MK", ne?) jsem to vycentroval a posunul níž / přidal `margin-top`. A ještě jsem odstranil tu modrou čáru v Myšlení. Myslím, že to bez ní vypadá lépe.
